#!/usr/bin/env python3
"""
Generate trampoline stubs for game logic functions being overridden.

When a game logic function is replaced by new C++ code, other ARM functions
in the original blob still call it at the original address via BL instructions.

A trampoline at the original address branches to the new C++ implementation.

Strategy:
  For each overridden function, emit a trampoline at the original offset
  within the ARM text section that loads the address of the new C++
  implementation and branches to it.

  ARM32 trampoline (Thumb interworking-safe):
    ldr pc, [pc, #-4]    ; load PC from literal pool
    .word <new_func_addr>

  Since we're linking everything together, we can use the same symbol name
  and let the linker resolve it — the trampoline uses a different name
  (tramp_<name>) that the linker redirects.

  Actually, simpler: just export the symbol with the original name and
  have the ARM blob skip it. The new C++ provides the real implementation.
  The original ARM code at this location is replaced by our trampoline.
"""

import subprocess
import sys
import re
from pathlib import Path


def get_function_info(libg: Path):
    """Extract function name, virtual address, size for all GLOBAL FUNC symbols."""
    result = subprocess.run(
        ["readelf", "-s", "--wide", str(libg)],
        capture_output=True, text=True, check=True
    )
    funcs = []
    for line in result.stdout.splitlines():
        parts = line.split()
        if len(parts) < 8:
            continue
        try:
            idx = int(parts[0].rstrip(':'))
        except ValueError:
            continue
        typ = parts[2]
        bind = parts[4]
        ndx = parts[6]
        name = parts[7] if len(parts) > 7 else ""

        if typ == "FUNC" and bind == "GLOBAL" and ndx != "UND" and name:
            value = int(parts[1], 16)
            size = int(parts[2])
            funcs.append((idx, name, value, size))

    return funcs


def get_text_section_info(libg: Path):
    """Get .text section offset and size from the ELF."""
    result = subprocess.run(
        ["readelf", "-S", str(libg)],
        capture_output=True, text=True, check=True
    )
    for line in result.stdout.splitlines():
        m = re.match(r'\s*\[.*\]\s+\.text\s+PROGBITS\s+(\S+)\s+(\S+)\s+(\S+)', line)
        if m:
            addr = int(m.group(1), 16)
            offset = int(m.group(2), 16)
            size = int(m.group(3), 16)
            return addr, offset, size
    raise RuntimeError("Could not find .text section")


def main():
    import argparse
    parser = argparse.ArgumentParser(description="Generate trampoline stubs")
    parser.add_argument("libg", type=Path, help="Path to original libg.so")
    parser.add_argument("symlist", type=Path, help="Symbol list (mangled names to override)")
    parser.add_argument("-o", "--output", type=Path, default=Path("trampolines.S"),
                        help="Output assembly file")
    args = parser.parse_args()

    libg_path = args.libg.resolve()
    text_addr, text_offset, text_size = get_text_section_info(libg_path)
    all_funcs = get_function_info(libg_path)

    sym_map = {}
    for idx, name, vaddr, size in all_funcs:
        sym_map[name] = (vaddr, size)

    # Read symbols to override
    with open(args.symlist) as f:
        overrides = set()
        for line in f:
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            parts = line.split()
            if len(parts) >= 2:
                overrides.add(parts[1])

    lines = [
        '# Auto-generated trampolines for overridden game logic functions',
        '# Generated by gen_trampolines.py',
        '# Each trampoline sits at the original function address and',
        '# branches to our C++ implementation.',
        '',
        '.syntax unified',
        '.arch armv7-a',
        '.arm',
        '',
    ]

    # For ARM mode, a trampoline can be:
    #   ldr pc, [pc, #-4]
    #   .word target_addr
    # This is 8 bytes total.
    #
    # For Thumb (which the original uses), a trampoline needs:
    #   ldr pc, [pc, #0]   ; 4 bytes (thumb encoding)
    #   .word target_addr   ; 4 bytes
    # But we need to handle interworking.
    #
    # Simplest approach: just export the original symbol name and
    # include the original code bytes. The new C++ also exports the
    # same symbol name. The linker with --allow-multiple-definition
    # picks the first definition (our C++ one if we order correctly).
    #
    # For internal ARM-to-game-logic calls, we need the ARM code to
    # call through the trampoline. We embed the trampoline instead
    # of the original code.
    #
    # For now: each trampoline is:
    #   .globl tramp_<name>
    #   tramp_<name>:
    #     b <name>     ; branch to C++ implementation (resolved by linker)
    #
    # The original ARM code will still call the original address.
    # This is the key challenge — see docs for the full approach.

    count = 0
    for name in sorted(overrides):
        if name not in sym_map:
            continue
        vaddr, size = sym_map[name]
        if size == 0:
            continue

        # Emit the original code as a trampoline section.
        # In the final .text layout, this sits at the original offset.
        file_offset = text_offset + (vaddr - text_addr)

        lines.extend([
            f'.section .text.trampoline,"ax",%progbits',
            f'.globl {name}',
            f'.type {name}, %function',
            f'{name}:',
        ])

        if size >= 8:
            # Keep original code (internal callers still work).
            # The symbol is overridden by our C++ via link order.
            lines.append(f'    .incbin "{libg_path}", {file_offset}, {size}')
        else:
            # Pad with NOPs if too small
            lines.append(f'    .incbin "{libg_path}", {file_offset}, {size}')
            lines.append(f'    .fill 8 - {size}, 1, 0x00')

        lines.append(f'.size {name}, {size}')
        lines.append('')
        count += 1

    with open(args.output, 'w') as f:
        f.write('\n'.join(lines))
        f.write('\n')

    print(f"Generated {count} trampolines in {args.output}")
    print("NOTE: Overridden functions use --allow-multiple-definition.")
    print("New C++ implementations must export the same mangled symbol.")


if __name__ == "__main__":
    main()
