#!/usr/bin/env python3
"""
Generate ARM assembly stubs for internal (non-game-logic) functions.

Each stub exports the original mangled symbol and embeds the original
ARM code bytes from the libg.so .text section using .incbin directives.

The stub layout:
  .globl <mangled_name>
  .type <mangled_name>, %function
  <mangled_name>:
      .incbin "<libg.so>", <offset>, <size>
  .size <mangled_name>, <size>
"""

import subprocess
import sys
import re
from pathlib import Path


def get_text_section_info(libg: Path):
    """Get .text section offset and size from the ELF."""
    result = subprocess.run(
        ["readelf", "-S", str(libg)],
        capture_output=True, text=True, check=True
    )
    for line in result.stdout.splitlines():
        m = re.match(r'\s*\[.*\]\s+\.text\s+PROGBITS\s+(\S+)\s+(\S+)\s+(\S+)', line)
        if m:
            addr = int(m.group(1), 16)
            offset = int(m.group(2), 16)
            size = int(m.group(3), 16)
            return addr, offset, size
    raise RuntimeError("Could not find .text section")


def get_function_info(libg: Path):
    """Extract function name, virtual address, size for all GLOBAL FUNC symbols."""
    result = subprocess.run(
        ["readelf", "-s", "--wide", str(libg)],
        capture_output=True, text=True, check=True
    )
    funcs = []
    for line in result.stdout.splitlines():
        parts = line.split()
        if len(parts) < 8:
            continue
        try:
            idx = int(parts[0].rstrip(':'))
        except ValueError:
            continue
        typ = parts[2]
        bind = parts[4]
        ndx = parts[6]
        name = parts[7] if len(parts) > 7 else ""

        if typ == "FUNC" and bind == "GLOBAL" and ndx != "UND" and name:
            value = int(parts[1], 16)
            size = int(parts[2])
            funcs.append((idx, name, value, size))

    return funcs


def main():
    import argparse
    parser = argparse.ArgumentParser(description="Generate ARM assembly stubs")
    parser.add_argument("libg", type=Path, help="Path to original libg.so")
    parser.add_argument("symlist", type=Path, help="Symbol list (one mangled name per line)")
    parser.add_argument("-o", "--output", type=Path, default=Path("arm_exports.S"),
                        help="Output assembly file")
    args = parser.parse_args()

    libg_path = args.libg.resolve()
    text_addr, text_offset, text_size = get_text_section_info(libg_path)
    all_funcs = get_function_info(libg_path)

    # Build map: mangled_name -> (vaddr, size)
    sym_map = {}
    for idx, name, vaddr, size in all_funcs:
        sym_map[name] = (vaddr, size)

    # Read symbols to include
    with open(args.symlist) as f:
        wanted = set()
        for line in f:
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            parts = line.split()
            if len(parts) >= 2:
                wanted.add(parts[1])

    # Generate assembly
    lines = [
        '# Auto-generated ARM stubs for internal functions',
        '# Generated by gen_arm_stubs.py',
        '# Original libg.so: ' + str(libg_path),
        '',
        '.syntax unified',
        '.arch armv7-a',
        '.arm',
        '',
    ]

    count = 0
    for name in sorted(wanted):
        if name not in sym_map:
            continue
        vaddr, size = sym_map[name]
        if size == 0:
            continue

        file_offset = text_offset + (vaddr - text_addr)
        lines.extend([
            f'.globl {name}',
            f'.type {name}, %function',
            f'{name}:',
            f'    .incbin "{libg_path}", {file_offset}, {size}',
            f'.size {name}, {size}',
            '',
        ])
        count += 1

    with open(args.output, 'w') as f:
        f.write('\n'.join(lines))
        f.write('\n')

    print(f"Generated {count} ARM stubs in {args.output}")


if __name__ == "__main__":
    main()
